#![feature(test)]

mod day_01_a;
mod day_01_b;
mod day_02_a;
mod day_02_b;
mod day_03_a;
mod day_03_b;
mod day_04_a;
mod day_04_b;
mod day_05_a;
mod day_05_b;
mod day_05_c;
mod day_06_a;
mod day_06_b;
mod day_07_a;
mod day_07_b;
mod day_08_a;
mod day_08_b;
mod day_09_a;
mod day_09_b;
mod day_10_a;
mod day_10_b;
mod day_11_a;
mod day_11_b;
// mod day_12_a;
// mod day_12_b;
// mod day_13_a;
// mod day_13_b;
// mod day_14_a;
// mod day_14_b;
// mod day_15_a;
// mod day_15_b;
// mod day_16_a;
// mod day_16_b;
// mod day_17_a;
// mod day_17_b;
// mod day_18_a;
// mod day_18_b;
// mod day_19_a;
// mod day_19_b;
// mod day_20_a;
// mod day_20_b;
// mod day_21_a;
// mod day_21_b;
// mod day_22_a;
// mod day_22_b;
// mod day_23_a;
// mod day_23_b;
// mod day_24_a;
// mod day_24_b;
// mod day_25_a;

pub fn run_all_days() {
    day_01_a::main("".to_string());
    day_01_b::main("".to_string());
    day_02_a::main("".to_string());
    day_02_b::main("".to_string());
    day_03_a::main("".to_string());
    day_03_b::main("".to_string());
    day_04_a::main("".to_string());
    day_04_b::main("".to_string());
    day_05_a::main("".to_string());
    day_05_b::main("".to_string());
    day_05_c::main("".to_string());
    day_06_a::main("".to_string());
    day_06_b::main("".to_string());
    day_07_a::main("".to_string());
    day_07_b::main("".to_string());
    day_08_a::main("".to_string());
    day_08_b::main("".to_string());
    day_09_a::main("".to_string());
    day_09_b::main("".to_string());
    day_10_a::main("".to_string());
    day_10_b::main("".to_string());
    day_11_a::main("".to_string());
    day_11_b::main("".to_string());
    // day_12_a::main("".to_string());
    // day_12_b::main("".to_string());
    // day_13_a::main("".to_string());
    // day_13_b::main("".to_string());
    // day_14_a::main("".to_string());
    // day_14_b::main("".to_string());
    // day_15_a::main("".to_string());
    // day_15_b::main("".to_string());
    // day_16_a::main("".to_string());
    // day_16_b::main("".to_string());
    // day_17_a::main("".to_string());
    // day_17_b::main("".to_string());
    // day_18_a::main("".to_string());
    // day_18_b::main("".to_string());
    // day_19_a::main("".to_string());
    // day_19_b::main("".to_string());
    // day_20_a::main("".to_string());
    // day_20_b::main("".to_string());
    // day_21_a::main("".to_string());
    // day_21_b::main("".to_string());
    // day_22_a::main("".to_string());
    // day_22_b::main("".to_string());
    // day_23_a::main("".to_string());
    // day_23_b::main("".to_string());
    // day_24_a::main("".to_string());
    // day_24_b::main("".to_string());
    // day_25_a::main("".to_string());
}